# Generated by Django 2.2.8 on 2020-01-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
