# Generated by Django 2.2.8 on 2020-01-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_redirect_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='destination',
            field=models.CharField(max_length=50),
        ),
    ]
