# Generated by Django 2.2.8 on 2019-12-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_documenttest'),
        ('blog', '0002_auto_20191206_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_fa',
        ),
        migrations.AddField(
            model_name='post',
            name='post_description',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='post_description', to='translation.TranslatedText'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='post_title', to='translation.TranslatedText'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='text', to='translation.TranslatedText'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='name', to='translation.TranslatedText'),
            preserve_default=False,
        ),
    ]
