# Generated by Django 2.2.8 on 2020-01-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtext',
            name='receivers',
            field=models.ManyToManyField(to='notification.Subscriber'),
        ),
    ]
